# Generated by Django 5.0.6 on 2024-05-16 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_follow_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
